name: Build and Publish Docs to GitHub Pages

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: 'build'
        shell: bash
        env:
          STORYBOOK_BASE_PATH: /plusauth-widget/
        run: |
          echo "::group::Build"
          bun i
          bun run build-storybook
          echo "::endgroup::"
      - name: 'upload'
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b
        with:
          path: storybook-static
      - id: deploy
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e
        with:
          token: ${{ github.token }}
